<?php

namespace Dive\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DiveEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiveEntityRepository extends EntityRepository
{

}
